# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighborhood',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
