# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190417_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=150)),
                ('phone_number', models.IntegerField(null=True)),
                ('id_number', models.IntegerField(null=True)),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Village')),
            ],
        ),
    ]
